[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"

[fuzz]
max_test_rejects = 2_147_483_648
runs = 512
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
